In [5]:
#|export
from fastai.vision.all import *
from huggingface_hub import from_pretrained_fastai, push_to_hub_fastai
repo ='jkokko/'

/opt/homebrew/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
#|export
models = {
    'resnet18': resnet18,
    'resnet34': resnet34,
    'resnet50': resnet50,
}

def train(model_name, epochs=1):
    if model_name not in models:
        raise ValueError(f"Model name '{model_name}' is not supported. Choose from: {list(models.keys())}")
 
    model = models[model_name]
    path = untar_data(URLs.IMAGENETTE_320,data=Path.cwd()/'data')
    dls = ImageDataLoaders.from_folder(path, valid='val', item_tfms=Resize(224), batch_tfms=Normalize.from_stats(*imagenet_stats),)
    learn = vision_learner(dls, model, metrics=accuracy, pretrained=True)
    learn.fine_tune(epochs)

    return learn

def train_all(epochs=1):
    for model_name in models:
        learn = train(model_name, epochs)
        push_to_hub_fastai(learner=learn, repo_id=repo + model_name)
        


In [97]:
train_all()

model.pkl: 100%|██████████| 47.1M/47.1M [00:04<00:00, 11.5MB/s]


model.pkl: 100%|██████████| 87.6M/87.6M [00:06<00:00, 13.5MB/s]


model.pkl: 100%|██████████| 103M/103M [00:07<00:00, 14.3MB/s] 


In [18]:
train('resnet50', epochs=3)

Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to /Users/juhokokko/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth
100%|██████████| 97.8M/97.8M [00:02<00:00, 35.9MB/s]


In [2]:
#|export
def load(model_name):
    learn = from_pretrained_fastai(repo_id=repo + model_name)
    return learn

In [3]:
import torch
input_data = torch.randn(1, 3, 224, 224)

In [7]:
# test that the model is loaded correctly
model = load('resnet18').model
model.eval()
with torch.no_grad(): 
    output = model(input_data)
    print(output)

assert output.shape == (1, 10), f"Expected output shape to be (1, 10), but got {output.shape}"

Fetching 4 files: 100%|██████████| 4/4 [00:00<00:00, 60567.57it/s]

tensor([[ 0.6667, -3.8730, -0.1876, -0.3519,  3.1502, -1.3503, -0.6039, -5.0665,
          2.6549,  3.5074]])


In [9]:
# test that the model is loaded correctly
model = load('resnet34').model
model.eval()
with torch.no_grad(): 
    output = model(input_data)
    print(output)

assert output.shape == (1, 10), f"Expected output shape to be (1, 10), but got {output.shape}"

Fetching 4 files: 100%|██████████| 4/4 [00:00<00:00, 65536.00it/s]

tensor([[-1.3935, -1.6609,  0.8618, -0.9563,  3.2318, -0.6594, -2.0422, -4.9644,
          4.3499,  2.3675]])


In [12]:
# test that the model is loaded correctly
model = load('resnet50').model
model.eval()
with torch.no_grad(): 
    output = model(input_data)
    print(output)

assert output.shape == (1, 10), f"Expected output shape to be (1, 10), but got {output.shape}"

Fetching 4 files: 100%|██████████| 4/4 [00:00<00:00, 108942.96it/s]

tensor([[-1.6896, -2.5800, -0.0600, -0.4307,  4.4927, -1.3391, -1.9423, -3.7715,
          6.5818,  5.5764]])


In [ ]:
#current_path = Path('.')
#learn.path = current_path
#learn.model_dir = 'models'
#learn.save('resnet18')

In [13]:
model = load('resnet18').model

Fetching 4 files: 100%|██████████| 4/4 [00:00<00:00, 78398.21it/s]


In [14]:
model = load('resnet34').model
model

Fetching 4 files: 100%|██████████| 4/4 [00:00<00:00, 86928.58it/s]


Sequential(
  (0): Sequential(
    (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (4): Sequential(
      (0): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      )
      (1): BasicBlock(
        (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  

In [15]:
model = load('resnet50').model
model

Fetching 4 files: 100%|██████████| 4/4 [00:00<00:00, 75234.15it/s]


Sequential(
  (0): Sequential(
    (0): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
    (1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU(inplace=True)
    (3): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
    (4): Sequential(
      (0): Bottleneck(
        (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
        (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
        (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
        (relu): ReLU(inplace=True)
        (downsample): Sequential(
          (0): Conv2d(64, 256